export const defaultValues = {
  postData: {
    title: "",
    description: "",
    postType: "RENT",
    currency: "ALL",
    type: "",
    postAdvertIndex: "FREE",
    brand: "",
    color: "",
    transmission: "AUTOMATIC",
    kilometers: "",
    fuel: "DIESEL",
    power: "",
    price: "",
    firstRegistration: new Date().getFullYear().toString(),
    engineSize: "",
    imageUrls: [],
  },
  userData: {
    username: "",
    password: "",
    firstName: "",
    lastName: "",
    address: "",
    city: "",
    country: "",
    email: "",
    phoneNumber: "",
  },
};
