import React from "react";

const Data = () => {
  return (
    <div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
      <div>Data</div>
    </div>
  );
};

export default Data;
